---
title: "Final Project"
author: "Jacob"
date: "2024-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(mosaic)
library(tidyr)
library(tidyverse)
```

Average number of bison sightings in Yellowstone national park, per year 

clean the data,

```{r}
 animals <- read.csv("wildlife.csv")
```


```{r}
buffalo <- animals%>%
  filter(Sighting.Animal=="Bison")
```

```{r}
convert_to_numbers <- function(column) {
  # Apply the transformation for each row in the column
  sapply(column, function(value) {
    # Handle "Less than X"
    if (grepl("Less than", value)) {
      number <- as.numeric(gsub("Less than ", "", value))
      return(number / 2)  # Estimate: return half of the number as a representative value
      
    # Handle "More than X"
    } else if (grepl("More than", value)) {
      number <- as.numeric(gsub("More than ", "", value))
      return(number + (number / 2))  # Estimate: return 1.5 times the number as a representative value

    # Handle "Y to Z"
    } else if (grepl("to", value)) {
      range_values <- as.numeric(strsplit(value, " to ")[[1]])
      return(mean(range_values))  # Take the average of the range

    # Return NA if the value is unrecognized
    } else {
      return(NA)
    }
  })
}

buffalo$Sighting.Quantity <- convert_to_numbers(buffalo$Sighting.Quantity)
```
```{r}
no_na <- drop_na(buffalo)
```

```{r}

ggplot(buffalo, aes(x=Sighting.Quantity, ))+
  geom_histogram()



```
```{r}
bison <- no_na%>%
  group_by(Observation.Year)%>%
  summarize(tot = sum(Sighting.Quantity),rows = n())

bison$average = bison$tot / bison$rows

```



```{r}
ggplot(bison, aes(x=average))+
  geom_histogram()
```


# chunks from Nik's Rmd File
```{r}
library(infer)
set.seed(356)
# Generate bootstrap distribution of means
bootobject_mean <- bison %>%
  # Specify the variable of interest
  specify(response = tot) %>%  
  # Generate 1000 bootstrap samples
  generate(reps = 1000, type = "bootstrap") %>% 
  # Calculate the mean of each bootstrap sample
 calculate(stat = "mean")*2
head(bootobject_mean)
```

```{r, echo = F}
histogram(~stat,
          xlab="sample mean",
          main="Bootstrap Distribution of sample mean",
          cex.main=0.6,data = bootobject_mean)

ggplot(bootobject_mean, aes(x = stat)) + geom_histogram(fill = 'darkorange', color = 'black', binwidth = 275) + labs(x = "Sample Mean", y ="Density", title = "Bootstrap Distribution of Twice the Sample Means") + theme_classic() + geom_vline(aes(xintercept = 1000), linetype = 1, color = 'red', linewidth = 1) + geom_vline(aes(xintercept = 1448.29), linetype = 2, linewidth = 1)
```


```{r,}
favstats(~stat, data = bootobject_mean)[c("mean","sd")]

```


```{r}
set.seed(356)
# Generate bootstrap distribution of medians
bootobject_median <- bison %>%
  # Specify the variable of interest
  specify(response = tot) %>%  
  # Generate 1000 bootstrap samples
  generate(reps = 1000, type = "bootstrap") %>% 
  # Calculate the median of each bootstrap sample
 calculate(stat = "median")*2
head(bootobject_median)
```



```{r}
histogram(~stat,
          xlab="sample median",
          main="Bootstrap Distribution of 2 sample median",
          cex.main=0.6,data = bootobject_median)

ggplot(bootobject_median, aes(x = stat)) + geom_histogram(fill = 'lightgreen', color = 'black', binwidth = 270) + labs(x = "Sample Median", y ="Density", title = "Boostrap Distribution of Twice the Sample Medians") + theme_classic() + geom_vline(aes(xintercept = 1000), linetype = 1, color = 'red', linewidth = 1) + geom_vline(aes(xintercept = 893), linetype = 2, linewidth = 1)
```

```{r,}
favstats(~stat, data = bootobject_median)[c("mean","sd")]
```


## Initial Distribution






